"""empty message

Revision ID: 8a2e1a8c9e75
Revises: 62bb346476b0
Create Date: 2023-01-30 21:08:13.423305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a2e1a8c9e75'
down_revision = '62bb346476b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('lastname', sa.String(length=255), nullable=False))
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'firstName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstName', sa.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('lastName', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###